version: '3'
services:
  db:
    image: "percona:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    image: webapp-test
    build: .
    deploy:
      mode: replicated
      replicas: 2
  frontend:
    image: "nginx:latest"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - app
    ports:
    - "8083:80"
 